name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src/ --max-line-length=120

      - name: Run tests
        run: |
          if [ -d "tests" ]; then pytest tests/; else echo "No tests directory found."; fi

      - name: Launch Gradio app (smoke test)
        run: |
          python -m pip install gradio
          python app.py --help || true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy step (placeholder)
        run: echo "Deploy logic goes here."
